<?xml version="1.0"?>
<package format="3">
  <name>ros2_aruco_position</name>
  <version>0.1.0</version>
  <description>ROS 2 ArUco pose estimation package that publishes TF frames for detected markers.</description>
  <maintainer email="zma40@sfu.ca">Zander Mao</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>python3-opencv</depend>
  <depend>rclpy</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
